#!/bin/bash
# Sync CODE only. Never touches data/ or public/data.* — those are
# generated by the user's scraper runs and must not be overwritten by a
# stale copy from elsewhere.
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEST="$1"
[ -z "$DEST" ] && { echo "usage: $0 <dest>"; exit 1; }
rsync -a \
  --exclude '__pycache__' --exclude '*.pyc' --exclude '.DS_Store' \
  --exclude '*.bak' --exclude 'logs/' \
  --exclude 'data/' \
  --exclude 'public/data.json' --exclude 'public/data.js' \
  "$SRC"/ "$DEST"/
echo "code synced (data/ and public/data.* left untouched)"
